user root;
worker_processes auto;
pid /tmp/nginx.pid;

events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;
    access_log /dev/stdout;
    error_log /dev/stderr;

    sendfile on;
    keepalive_timeout 65;
    port_in_redirect off;

    server {
        listen 80;
        server_name _;
        root /usr/share/nginx/html;
        index landing.html index.html;

        location / {
            try_files $uri $uri/ =404;
        }
    }
}
