import type { Metadata, Viewport } from 'next';
import type { ReactNode } from 'react';
import { cookies } from 'next/headers';
import { IBM_Plex_Mono, IBM_Plex_Sans, IBM_Plex_Sans_Arabic } from 'next/font/google';
import './_kit/tokens.css';       // generated by scripts/sync-kit.mjs from ../kit (single source of truth)
import './_kit/base.css';
import './_kit/components.css';
import './globals.css';
import { Providers } from '@/components/Providers';
import type { Lang } from '@/lib/types';

const ar = IBM_Plex_Sans_Arabic({ subsets: ['arabic', 'latin'], weight: ['400', '500', '600', '700'], variable: '--font-ar', display: 'swap' });
const en = IBM_Plex_Sans({ subsets: ['latin'], weight: ['400', '500', '600', '700'], variable: '--font-en', display: 'swap' });
const mono = IBM_Plex_Mono({ subsets: ['latin'], weight: ['400', '500'], variable: '--font-mono', display: 'swap' });

export const metadata: Metadata = {
  title: 'السوق · alSooq',
  description: 'alSooq — marketplace, mobility and logistics on one bilingual design system.',
};
export const viewport: Viewport = {
  width: 'device-width', initialScale: 1, viewportFit: 'cover', interactiveWidget: 'resizes-content',
  themeColor: '#F6F1E7',   // matches --aq-sand (a meta value cannot read a CSS variable)
};

// Reading the cookie makes pages render per request — the price of a correct lang/dir on first paint (no RTL↔LTR flash).
export default async function RootLayout({ children }: { children: ReactNode }) {
  const lang: Lang = (await cookies()).get('aq-lang')?.value === 'en' ? 'en' : 'ar';
  return (
    <html lang={lang} dir={lang === 'ar' ? 'rtl' : 'ltr'} className={`${ar.variable} ${en.variable} ${mono.variable}`}>
      <body><Providers lang={lang}>{children}</Providers></body>
    </html>
  );
}
